@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTY0MDc4NTE5NSwiZXhwIjoxNjQxMzg5OTk1fQ.okJswXtKo1AkJUqm8BAXFGM-YgKQFMoK4ZI4iJLZHog
@json = application/json
##################

### Sign Up
POST http://localhost:4000/users/register
content-type: {{json}}

{ 
  "firstName": "MMMM",
  "lastName": "MMMM",
  "username": "MyUserName",
  "password": "123456"
}




### Login
POST http://localhost:4000/users/authenticate
content-type: {{json}}

{ 
  "username": "xsd",
  "password": "123456"
}



### Users
GET http://localhost:4000/
content-type: {{json}}
Authorization: {{token}}






### All Users
GET http://localhost:4000/users
content-type: {{json}}
Authorization: {{token}}



### Current User
GET http://localhost:4000/users/current
content-type: {{json}}
Authorization: {{token}}


### User by Id
GET http://localhost:4000/users/2
content-type: {{json}}
Authorization: {{token}}











### OLD ###


### View All

GET http://localhost:4000/api/users




### Delete

DELETE http://localhost:4000/api/users/8




### Add

POST http://localhost:4000/api/users
content-type: application/json

{ 
  "username": "Bmp",
  "email": "info@now.com",
  "phone": "132154"
}




### Update

PUT http://localhost:4000/api/users/2
content-type: application/json

{ 
  "username": "MMMM",
  "email": "yyyyyyyy@now.com",
  "phone": "132154"
}


